"""Expected column names for all USports functions."""

expected_basketball_standings_columns = [
    "team_name",
    "games_played",
    "total_wins",
    "total_losses",
    "win_percentage",
    "total_points",
    "total_points_against",
    "conference",
]


expected_basketball_team_stats_columns = [
    "team_name",
    "games_played",
    "points_per_game",
    "field_goal_made",
    "field_goal_attempted",
    "field_goal_percentage",
    "three_pointers_made",
    "three_pointers_attempted",
    "three_point_percentage",
    "free_throws_made",
    "free_throws_attempted",
    "free_throw_percentage",
    "offensive_rebounds_per_game",
    "defensive_rebounds_per_game",
    "total_rebounds_per_game",
    "rebound_margin",
    "assists_per_game",
    "turnovers_per_game",
    "steals_per_game",
    "blocks_per_game",
    "team_fouls_per_game",
    "offensive_efficiency",
    "defensive_efficiency",
    "net_efficiency",
    "field_goal_made_against",
    "field_goal_attempted_against",
    "field_goal_percentage_against",
    "three_pointers_made_against",
    "three_pointers_attempted_against",
    "three_point_percentage_against",
    "offensive_rebounds_per_game_against",
    "defensive_rebounds_per_game_against",
    "total_rebounds_per_game_against",
    "rebound_margin_against",
    "assists_per_game_against",
    "turnovers_per_game_against",
    "steals_per_game_against",
    "blocks_per_game_against",
    "team_fouls_per_game_against",
    "points_per_game_against",
    "conference",
]


expected_basketball_players_columns = [
    "lastname_initials",
    "first_name",
    "school",
    "games_played",
    "games_started",
    "minutes_played",
    "field_goal_made",
    "field_goal_attempted",
    "field_goal_percentage",
    "three_pointers_made",
    "three_pointers_attempted",
    "three_pointers_percentage",
    "free_throws_made",
    "free_throws_attempted",
    "free_throws_percentage",
    "total_points",
    "offensive_rebounds",
    "defensive_rebounds",
    "total_rebounds",
    "assists",
    "turnovers",
    "steals",
    "blocks",
    "personal_fouls",
    "disqualifications",
]

expected_football_standings_columns = [
    "team_name",
    "games_played",
    "total_wins",
    "total_losses",
    "win_percentage",
    "total_points",
    "total_points_against",
    "conference",
]
expected_football_column_names = [
    "team_name",
    "games_played",
    "touchdowns",
    "field_goals",
    "extra_points",
    "two_point_conversions",
    "defensive_extra_points",
    "safeties",
    "points",
    "points_per_game",
    "rushing_yards",
    "passing_yards",
    "total_offense",
    "yards_per_game",
    "pass_completions",
    "pass_attempts",
    "pass_interceptions",
    "passing_yards_per_game",
    "yards_per_attempt",
    "yards_per_completion",
    "passing_touchdowns",
    "rushing_attempts",
    "rushing_yards_per_game",
    "rushing_average",
    "rushing_touchdowns",
    "total_first_downs",
    "rushing_first_downs",
    "passing_first_downs",
    "penalty_first_downs",
    "first_downs_per_game",
    "third_down_conversions_made",
    "third_down_attempts",
    "third_down_conversion_percentage",
    "fourth_down_conversions_made",
    "fourth_down_attempts",
    "fourth_down_conversion_percentage",
    "kick_return_count",
    "kick_return_yards",
    "kickoff_return_average",
    "punt_return_count",
    "punt_return_yards",
    "punt_return_average",
    "field_goal_made",
    "field_goal_attempt",
    "field_goal_percentage",
    "extra_point_made",
    "extra_point_attempt",
    "extra_point_percentage",
    "punt_count",
    "punt_yards",
    "punt_average",
    "kickoff_count",
    "kickoff_yards",
    "kickoff_average",
    "scores_made",
    "scores_attempt",
    "red_zone_percentage",
    "touchdowns_made",
    "touchdowns_attempt",
    "touchdown_percentage",
    "fumbles",
    "fumbles_lost",
    "fumble_recoveries",
    "interceptions",
    "interception_yards",
    "interception_average",
    "interception_touchdowns",
    "tackles",
    "sacks",
    "penalties",
    "penalties_per_game",
    "penalty_yards",
    "penalty_yards_per_game",
    "tackles_per_game",
    "time_of_possession",
    "home_attendance",
    "average_home_attendance",
]


expected_football_players_df_column = [
    # Passing stats
    "games_played",
    "pass_completions",
    "pass_attempts",
    "completion_percentage",
    "passing_yards",
    "passing_yards_per_game",
    "yards_per_attempt",
    "passing_touchdowns",
    "interceptions",
    "longest_pass",
    "passing_efficiency",
    # Rushing stats
    "rushing_attempts",
    "rushing_yards",
    "rushing_yards_per_game",
    "yards_per_carry",
    "rushing_touchdowns",
    "longest_rush",
    "fumbles",
    "fumbles_lost",
    # Receiving stats
    "receptions",
    "receptions_per_game",
    "receiving_yards",
    "receiving_yards_per_game",
    "yards_per_reception",
    "receiving_touchdowns",
    "longest_reception",
    # Kicking stats
    "field_goals_made",
    "field_goals_attempted",
    "field_goal_percentage",
    "longest_field_goal",
    "extra_points_made",
    "extra_points_attempted",
    "extra_point_percentage",
    "kicking_points",
    # Punting stats
    "punts",
    "punting_yards",
    "yards_per_punt",
    "longest_punt",
    "punts_inside_20",
    "fair_catches",
    "touchbacks",
    "blocked_punts",
    # Return stats
    "kick_returns",
    "kick_return_yards",
    "yards_per_kick_return",
    "kick_return_touchdowns",
    "longest_kick_return",
    "punt_returns",
    "punt_return_yards",
    "yards_per_punt_return",
    "punt_return_touchdowns",
    "longest_punt_return",
    # All-Purpose yards stats
    "receiving_yards",
    "punt_return_yards",
    "kick_return_yards",
    "total_yards",
    "yards_per_game",
    # Scoring stats
    "total_points",
    "points_per_game",
    "interception_return_touchdowns",
    "fumble_return_touchdowns",
    "two_point_conversions",
    "miscellaneous_touchdowns",
    # Defensive stats
    "solo_tackles",
    "assisted_tackles",
    "total_tackles",
    "tackles_per_game",
    "sacks",
    "sack_yards",
    "tackles_for_loss",
    "tackles_for_loss_yards",
    "forced_fumbles",
    "fumble_recoveries",
    "fumble_recovery_yards",
    "interception_return_yards",
    "pass_breakups",
    "blocked_kicks",
]

expected_ice_hockey_standings_columns = [
    "team_name",
    "games_played",
    "total_wins",
    "total_losses",
    "goals_for",
    "goals_against",
    "total_points",
    "conference",
]

expected_ice_hockey_team_stats_columns = [
    "team_name",
    "games_played",
    "goals",
    "assists",
    "goals_per_game",
    "shots",
    "penalty_minutes",
    "power_play_goals",
    "power_play_opportunities",
    "power_play_percentage",
    "power_play_goals_against",
    "times_short_handed",
    "penalty_kill_percentage",
    "short_handed_goals",
    "short_handed_goals_against",
    "goals_against",
    "goals_against_average",
    "saves",
    "save_percentage",
    "empty_net_goals_against",
    "conference",
]

expected_ice_hockey_players_columns = [
    "lastname_initials",
    "first_name",
    "school",
    "games_played",
    "goals",
    "assists",
    "points",
    "penalty_minutes",
    "plus_minus",
    "power_play_goals",
    "short_handed_goals",
    "empty_net_goals",
    "game_winning_goals",
    "game_tying_goals",
    "hat_tricks",
    "shots_on_goal",
    "role",
    "minutes_played",
    "goals_against",
    "goals_against_average",
    "saves",
    "save_percentage",
    "wins",
    "losses",
    "ties",
    "win_percentage",
]

expected_volleyball_standings_columns = [
    "team_name",
    "games_played",
    "total_wins",
    "total_losses",
    "win_percentage",
    "sets_for",
    "sets_against",
    "points",
    "conference",
]

expected_volleyball_team_stats_columns = [
    "team_name",
    "matches_played",
    "sets_played",
    # Offensive stats
    "kills",
    "kills_per_set",
    "errors",
    "total_attacks",
    "hitting_percentage",
    "assists",
    "assists_per_set",
    "points",
    "points_per_set",
    # Defensive stats
    "digs",
    "digs_per_set",
    "block_solos",
    "block_assists",
    "total_blocks",
    "blocks_per_set",
    # Serve/Receive stats
    "service_aces",
    "service_aces_per_set",
    "service_errors",
    "receptions",
    "reception_errors",
    "conference",
]

expected_volleyball_players_columns = [
    "lastname_initials",
    "first_name",
    "school",
    "matches_played",
    "sets_played",
    # Offensive stats
    "kills",
    "kills_per_set",
    "errors",
    "total_attacks",
    "total_attacks_per_set",
    "hitting_percentage",
    "assists",
    "assists_per_set",
    "points",
    "points_per_set",
    # Defensive stats
    "digs",
    "digs_per_set",
    "block_solos",
    "block_assists",
    "total_blocks",
    "blocks_per_set",
    # Serve/Receive stats
    "serve_attempts",
    "service_aces",
    "service_aces_per_set",
    "service_errors",
    "receptions",
    "reception_errors",
]