expected_basketball_reg_season_column_names = [
    "team_name",
    "points_per_game",
    "games_played",
    "total_points",
    "total_wins",
    "total_losses",
    "win_percentage",
    "total_points_against",
    "field_goal_made",
    "field_goal_attempted",
    "field_goal_percentage",
    "three_pointers_made",
    "three_point_percentage",
    "three_pointers_attempted",
    "free_throws_made",
    "free_throws_attempted",
    "free_throw_percentage",
    "offensive_rebounds_per_game",
    "defensive_rebounds_per_game",
    "total_rebounds_per_game",
    "rebound_margin",
    "assists_per_game",
    "turnovers_per_game",
    "steals_per_game",
    "blocks_per_game",
    "team_fouls_per_game",
    "offensive_efficiency",
    "defensive_efficiency",
    "net_efficiency",
    "field_goal_made_against",
    "field_goal_attempted_against",
    "field_goal_percentage_against",
    "three_pointers_made_against",
    "three_pointers_attempted_against",
    "three_point_percentage_against",
    "offensive_rebounds_per_game_against",
    "defensive_rebounds_per_game_against",
    "total_rebounds_per_game_against",
    "rebound_margin_against",
    "assists_per_game_against",
    "turnovers_per_game_against",
    "steals_per_game_against",
    "blocks_per_game_against",
    "team_fouls_per_game_against",
    "points_per_game_against",
    "conference",
]

expected_football_playoffs_season_column_names = [
    "team_name",
    "games_played",
    "touchdowns",
    "field_goals",
    "extra_points",
    "two_point_conversions",
    "defensive_extra_points",
    "safeties",
    "points",
    "points_per_game",
    "rushing_yards",
    "passing_yards",
    "total_offense",
    "yards_per_game",
    "pass_completions",
    "pass_attempts",
    "pass_interceptions",
    "passing_yards_per_game",
    "yards_per_attempt",
    "yards_per_completion",
    "passing_touchdowns",
    "rushing_attempts",
    "rushing_yards_per_game",
    "rushing_average",
    "rushing_touchdowns",
    "total_first_downs",
    "rushing_first_downs",
    "passing_first_downs",
    "penalty_first_downs",
    "first_downs_per_game",
    "third_down_conversions_made",
    "third_down_attempts",
    "third_down_conversion_percentage",
    "fourth_down_conversions_made",
    "fourth_down_attempts",
    "fourth_down_conversion_percentage",
    "kick_return_count",
    "kick_return_yards",
    "kickoff_return_average",
    "punt_return_count",
    "punt_return_yards",
    "punt_return_average",
    "field_goal_made",
    "field_goal_attempt",
    "field_goal_percentage",
    "extra_point_made",
    "extra_point_attempt",
    "extra_point_percentage",
    "punt_count",
    "punt_yards",
    "punt_average",
    "kickoff_count",
    "kickoff_yards",
    "kickoff_average",
    "scores_made",
    "scores_attempt",
    "red_zone_percentage",
    "touchdowns_made",
    "touchdowns_attempt",
    "touchdown_percentage",
    "fumbles",
    "fumbles_lost",
    "fumble_recoveries",
    "interceptions",
    "interception_yards",
    "interception_average",
    "interception_touchdowns",
    "tackles",
    "sacks",
    "penalties",
    "penalties_per_game",
    "penalty_yards",
    "penalty_yards_per_game",
    "tackles_per_game",
    "time_of_possession",
    "home_attendance",
    "average_home_attendance",
]

expected_basketball_playoffs_season_column_names = {
    "team_name": str,
    "points_per_game": float,
    "games_played": int,
    "field_goal_made": int,
    "field_goal_attempted": int,
    "field_goal_percentage": float,
    "three_pointers_made": int,
    "three_point_percentage": float,
    "three_pointers_attempted": int,
    "free_throws_made": int,
    "free_throws_attempted": int,
    "free_throw_percentage": float,
    "offensive_rebounds_per_game": float,
    "defensive_rebounds_per_game": float,
    "total_rebounds_per_game": float,
    "rebound_margin": float,
    "assists_per_game": float,
    "turnovers_per_game": float,
    "steals_per_game": float,
    "blocks_per_game": float,
    "team_fouls_per_game": float,
    "offensive_efficiency": float,
    "defensive_efficiency": float,
    "net_efficiency": float,
    "field_goal_made_against": int,
    "field_goal_attempted_against": int,
    "field_goal_percentage_against": float,
    "three_pointers_made_against": int,
    "three_pointers_attempted_against": int,
    "three_point_percentage_against": float,
    "offensive_rebounds_per_game_against": float,
    "defensive_rebounds_per_game_against": float,
    "total_rebounds_per_game_against": float,
    "rebound_margin_against": float,
    "assists_per_game_against": float,
    "turnovers_per_game_against": float,
    "steals_per_game_against": float,
    "blocks_per_game_against": float,
    "team_fouls_per_game_against": float,
    "points_per_game_against": float,
    "conference": str,
}

expected_basketball_players_df_columns = [
    "lastname_initials",
    "first_name",
    "school",
    "games_played",
    "games_started",
    "minutes_played",
    "field_goal_made",
    "field_goal_attempted",
    "field_goal_percentage",
    "three_pointers_made",
    "three_pointers_attempted",
    "three_pointers_percentage",
    "free_throws_made",
    "free_throws_attempted",
    "free_throws_percentage",
    "total_points",
    "offensive_rebounds",
    "defensive_rebounds",
    "total_rebounds",
    "assists",
    "turnovers",
    "steals",
    "blocks",
    "personal_fouls",
    "disqualifications",
]
