from typing import Literal

ConferenceType = Literal["OUA", "RSEQ", "CW", "AUS"]

SeasonType = Literal["regular", "playoffs", "championship"]

# Usport teams
TeamName = Literal[
    "Acadia",
    "Alberta",
    "Algoma",
    "Bishop's",
    "Brandon",
    "Brock",
    "Calgary",
    "Cape Breton",
    "Carleton",
    "Concordia",
    "Dalhousie",
    "Guelph",
    "Lakehead",
    "Laurentian",
    "Laurier",
    "Laval",
    "Lethbridge",
    "MacEwan",
    "Manitoba",
    "McGill",
    "McMaster",
    "Memorial",
    "Montreal",
    "Mount Royal",
    "Nipissing",
    "Ontario Tech",
    "Ottawa",
    "Queen's",
    "Regina",
    "RMC",
    "Saint Mary's",
    "Saskatchewan",
    "Sherbooke",
    "StFX",
    "Thompson Rivers",
    "Toronto",
    "Toronto Metropolitan",
    "Trent",
    "Trinity Western",
    "UBC",
    "UBC Okanagan",
    "UFV",
    "UNB",
    "UNBC",
    "UPEI",
    "UQAM",
    "Victoria",
    "Waterloo",
    "Western",
    "Windsor",
    "Winnipeg",
    "York",
]
