"""Contains mappings and configurations for team statistics, player statistics, conferences, and standings."""

from usports.utils.constants import AUS, CW, OUA, RSEQ

TEAM_STATS_COLUMNS_TYPE_MAPPING: list[dict[str, type]] = [
    {
        "field_goal_made": int,
        "field_goal_percentage": float,
        "three_pointers_made": int,
        "three_point_percentage": float,
        "free_throws_made": int,
        "free_throw_percentage": float,
        "points_per_game": float,
    },
    {
        "offensive_rebounds_per_game": float,
        "defensive_rebounds_per_game": float,
        "total_rebounds_per_game": float,
        "rebound_margin": float,
    },
    {
        "turnovers_per_game": float,
        "steals_per_game": float,
        "blocks_per_game": float,
        "assists_per_game": float,
    },
    {
        "team_fouls_per_game": float,
        "offensive_efficiency": float,
        "net_efficiency": float,
    },
    {
        "field_goal_made_against": int,
        "field_goal_percentage_against": float,
        "three_pointers_made_against": int,
        "three_point_percentage_against": float,
        "points_per_game_against": float,
    },
    {
        "offensive_rebounds_per_game_against": float,
        "defensive_rebounds_per_game_against": float,
        "total_rebounds_per_game_against": float,
        "rebound_margin_against": float,
    },
    {
        "turnovers_per_game_against": float,
        "steals_per_game_against": float,
        "blocks_per_game_against": float,
        "assists_per_game_against": float,
    },
    {
        "team_fouls_per_game_against": float,
        "defensive_efficiency": float,
        "net_efficiency_against": float,
    },
]


TEAM_CONFERENCES = {
    "Acadia": AUS,
    "Alberta": CW,
    "Algoma": OUA,
    "Bishop's": RSEQ,
    "Brandon": CW,
    "Brock": OUA,
    "Calgary": CW,
    "Cape Breton": AUS,
    "Carleton": OUA,
    "Concordia": RSEQ,
    "Dalhousie": AUS,
    "Guelph": OUA,
    "Lakehead": OUA,
    "Laurentian": OUA,
    "Laurier": OUA,
    "Laval": RSEQ,
    "Lethbridge": CW,
    "MacEwan": CW,
    "Manitoba": CW,
    "McGill": RSEQ,
    "McMaster": OUA,
    "Memorial": AUS,
    "Mount Royal": CW,
    "Nipissing": OUA,
    "Ontario Tech": OUA,
    "Ottawa": OUA,
    "Queen's": OUA,
    "Regina": CW,
    "Saint Mary's": AUS,
    "Saskatchewan": CW,
    "StFX": AUS,
    "Thompson Rivers": CW,
    "Toronto": OUA,
    "Toronto Metropolitan": OUA,
    "Trinity Western": CW,
    "UBC": CW,
    "UBC Okanagan": CW,
    "UFV": CW,
    "UNB": AUS,
    "UNBC": CW,
    "UPEI": AUS,
    "UQAM": RSEQ,
    "Victoria": CW,
    "Waterloo": OUA,
    "Western": OUA,
    "Windsor": OUA,
    "Winnipeg": CW,
    "York": OUA,
}

STANDINGS_COLUMNS_TYPE_MAPPING: dict[str, type] = {
    "team_name": str,
    "games_played": int,
    "total_wins": int,
    "total_losses": int,
    "ties": int,
    "win_percentage": float,
    "total_points": int,
    "total_points_against": int,
}

STATS_GROUP_OPTIONS = {
    "Offense Shooting": "#sh-0",
    "Off Rebounding": "#rb-0",
    "Off Ball Control": "#bc-0",
    "Off Efficiency": "#eff-0",
    "Defense Shooting": "#dsh-0",
    "Def Rebounding": "#drb-0",
    "Defense Ball Control": "#dbc-0",
    "Def Efficiency": "#deff-0",
}


PLAYER_STATS_COLUMNS_TYPE_MAPPING: list[dict[str, type]] = [
    {
        "minutes_played": int,
        "field_goal_made": int,
        "field_goal_percentage": float,
        "three_pointers_made": int,
        "three_pointers_percentage": float,
        "free_throws_made": int,
        "free_throws_percentage": float,
        "total_points": int,
    },
    {
        "offensive_rebounds": int,
        "defensive_rebounds": int,
        "total_rebounds": int,
        "assists": int,
        "turnovers": int,
        "steals": int,
        "blocks": int,
    },
    {
        "personal_fouls": int,
        "disqualifications": int,
        "assist_to_turnover_ratio": float,
    },
]

PLAYER_SORT_CATEGORIES = [
    "pts",
    "gp",
    "gs",
    "min",
    "fgp",
    "fgpt",
    "fgp3",
    "fgpt3",
    "ftp",
    "ftpt",
    "oreb",
    "dreb",
    "treb",
    "ast",
    "to",
    "stl",
    "blk",
    "pf",
    "dq",
    "ato",
]
